export { FexoraClient } from "./client";
export { ApiProvider } from "./provider";
export { setApiClient, queryKeys } from "./hooks";

// Re-export all hooks
export {
  useMe,
  useLogin,
  useRegister,
  useRefreshToken,
  useLogout,
  useProfile,
  useUpdateProfile,
  useUploadAvatar,
  useContent,
  useMyContent,
  useFeed,
  useInfiniteFeed,
  useCreateContent,
  useUploadContentMedia,
  useSubmitContent,
  useComments,
  useCreateComment,
  useDeleteComment,
  useThreads,
  useMessages,
  useSendMessage,
  useMarkThreadRead,
  useWalletBalance,
  useTransactions,
  useTopup,
  useUnlockContent,
  useUnlockPpvMessage,
  useCreateReport,
  useReports,
  useReport,
  useResolveReport,
  useHighlights,
  useHighlightItems,
  useCreateHighlight,
  useDeleteHighlight,
} from "./hooks";

// Re-export all types
export type {
  RegisterRequest,
  LoginRequest,
  RefreshRequest,
  AuthResponse,
  UserInfo,
  UpdateProfileRequest,
  ProfileResponse,
  CreateContentRequest,
  ContentResponse,
  CommentResponse,
  CreateCommentRequest,
  SendMessageRequest,
  ThreadResponse,
  MessageResponse,
  WalletResponse,
  TransactionResponse,
  TopupRequest,
  TopupResponse,
  UnlockRequest,
  UnlockResponse,
  CreateReportRequest,
  ResolveReportRequest,
  ReportResponse,
  HighlightResponse,
  HighlightItemResponse,
  CreateHighlightRequest,
  PaginationParams,
} from "./types";
